name: Check.Utilities

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        required: true
        description: Environment name
        options:
          - dev
          - stage
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

permissions:
  id-token: write
  contents: write
  pull-requests: write


jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changelog.outputs.changed }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
             
      - name: Preview outputs                             
        run: echo "$Hello World"
        
  #The below job ensures that sonar dashboard has a new analysis based on main branch with the new version
  sonar-qube:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Sonar
        if: contains(github.event.head_commit.message, 'Merge pull request') || github.event_name == 'workflow_dispatch' 
        run: echo "$Hello World"