name: Check.Utilities

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        required: true
        description: Environment name
        options:
          - dev
          - stage
  push:
    branches:
      - main
    paths:
      - 'CHANGELOG.md'

permissions:
  id-token: write
  contents: write
  pull-requests: write


jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changelog.outputs.changed }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
             
      - name: Preview outputs                             
        run: echo "$Hello World"

      - name: Check if CHANGELOG.md is modified
        id: check_changelog
        run: |
          # Fetch all branches to ensure we have the latest `main` reference
          git fetch --all
          git diff --name-only origin/main...$GITHUB_SHA
      
          # Compare the latest commit on `main` (origin/main) with the current commit ($GITHUB_SHA)
          if git diff --name-only origin/main...$GITHUB_SHA | grep -q 'CHANGELOG.md'; then
            echo "CHANGELOG.md was modified."
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not modified."
            echo "changed=false" >> $GITHUB_ENV
          fi
        
  #The below job ensures that sonar dashboard has a new analysis based on main branch with the new version
  sonar-qube:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Sonar
        if: ${{ needs.check_changelog.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' }} 
        run: echo "$Hello World"