name: Check.Utilities

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        required: true
        description: Environment name
        options:
          - dev
          - stage
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'CHANGELOG.md'

permissions:
  id-token: write
  contents: write
  pull-requests: write


jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_changelog.outputs.changed }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
             
      - name: Preview outputs                             
        run: echo "$Hello World"

      - name: Check if CHANGELOG.md is modified
        id: check_changelog
        run: |
          # If it's a PR, check the files changed in the PR
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            echo "This is a pull request."
            files_changed=$(jq -r '.pull_request.changed_files' <<< "${{ github.event }}")
            if [[ "$files_changed" == *"CHANGELOG.md"* ]]; then
              echo "CHANGELOG.md was modified in this PR."
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "CHANGELOG.md was not modified in this PR."
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          else
            # If it's a direct push to main, check if CHANGELOG.md is in the diff
            echo "This is a direct push to main."
            git fetch --all  # Fetch all branches
            if git diff --name-only origin/main...$GITHUB_SHA | grep -q 'CHANGELOG.md'; then
              echo "CHANGELOG.md was modified."
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "CHANGELOG.md was not modified."
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
          fi
        
  #The below job ensures that sonar dashboard has a new analysis based on main branch with the new version
  sonar-qube:
    runs-on: ubuntu-latest
    needs: set-vars
    steps:
      - name: Sonar
        if: ${{ needs.check_changelog.outputs.changed == 'true' || github.event_name == 'workflow_dispatch' }} 
        run: echo "$Hello World"